name: test
on: [push]

jobs:
  test:
    name: Build and Playwright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24.11.0"
          cache: npm
      - run: npm ci
      - run: npm run playwright:install:ci
      - run: npm run build
      - run: npm run test:headless
